### ISSUE TITLE
Als [geölst] markierte Beiträge mit entsprechendem Tag versehen

### ISSUE THREAD

**Issue by pierres** [archlinux-de/flarum-import-fluxbb#1]
Ich denke wir müsste zwei Digne tun:
* programmatisch einen Tag für "gelöst" anlegen. (wir brauchen die Id)
* Uns eine Regel überlegen z.B. das "[gelöst]" aus dem Titel entfernen und die Tag-Id dem Thread hinzufügen.

**Comment by conqp** [comment]
Ich habe mal auf die Schnelle ein RegEx zusammengeschustert, welche die meisten Tippvarianten berücksichtigen sollte:
```regex
[\[\(][Gg][Ee][Ll](?:[Öö]|[Oo][Ee])[Ssß][Tt][\]\)]
```
Man könnte den Titel des alten Beitrags danach durchsuchen (an beliebiger Stelle, da bei einigen Threads es am Ende steht) und dann entsprechend den Tag hinzufügen (`Topics.execute()`).

**Comment by pierres** [comment]
Hier ein erster Wurf; ich habe die Regel nach etwas Suchen in der DB erweitert. So treffen wir immerhin 3875 Themen.
